[package]
name = "geojson-rstar"
version = "0.1.0"
authors = ["Boyd Johnson <johnson.boyd@gmail.com>"]
edition = "2018"

[dependencies]
geo = "^0.14"
geojson = "^0.16"
num-traits = "^0.2"
rstar = "^0.8"
serde_json = "~1.0"
